import { clamp, heightAt, canWalk, riverX, deposits, HALF } from './world.mjs';
import { emptyCargo, addCargo } from './cargo.mjs';
import { releaseCart, ensureHauling } from './hauling.mjs';

export const COMMAND_HELP = {
  travel: ['tp camp|shop|assay|creek|ghost|fox|pay1..pay4 — named destinations', 'tp X Z [Y] — coordinates in metres; optional absolute height', 'tp @"Player Name" — go beside a friend; tp v2 / m3 / c1 goes beside equipment', 'back — return to your previous teleport position', 'mark NAME / marks / tp NAME — save, list and visit personal bookmarks', 'fly [on|off] / noclip — fly through obstacles; Space up, Ctrl down, Shift faster', 'speed 1..10 — walking and flight multiplier; speed 1 restores normal', 'jump 1..5 — jump multiplier; jump 1 restores normal', 'safe [on|off] / god — prevent tumbles (survival/death is not implemented)', 'recover / heal / unstuck — get up and move onto safe ground'],
  money: ['money AMOUNT / money add AMOUNT — add dollars to the crew treasury', 'money set AMOUNT / cash AMOUNT — set cash, or cash adds dollars', 'gold GRAMS — add recovered gold to your own pouch', 'bank / sell — sell your pouch from anywhere at the normal assay rate'],
  gear: ['give all — all personal upgrades, washer kits and purchase unlocks', 'give sieve|shovel|bucket|boots — grant a personal upgrade', 'give rocker|sluice|washplant — grant a washer kit', 'unlock all / unlock ID — bypass purchase prerequisites', 'spawn wheelbarrow|rocker|sluice|washplant|excavator|truck|hydraulic — place equipment', 'fill [KG] [GRAMS] — add test gravel and contained gold to your held container', 'time 0..24 / day NUMBER — change the world clock'],
  info: ['where / status — coordinates, map size, cash and cheat settings', 'players — crew names, IDs and coordinates', 'equipment — equipment IDs and coordinates; use tp ID', 'help [travel|money|gear|info] — command list', 'reset — normal movement, flight off, tumble protection off', 'clear — clear console output; Up/Down command history; Tab autocomplete']
};
export const DESTINATIONS=['camp','shop','assay','creek','ghost','fox','pay1','pay2','pay3','pay4'];
export const COMMANDS=['help','tp','back','mark','marks','fly','noclip','land','speed','jump','safe','god','recover','heal','unstuck','money','cash','gold','bank','sell','give','unlock','spawn','fill','time','day','where','status','players','equipment','reset','clear'];
const reply=(lines,extra={})=>({ok:true,console:true,message:'',lines:Array.isArray(lines)?lines:[lines],...extra});
const fail=message=>({...reply(message),ok:false});
const number=(s,min,max)=>{if(s===undefined||s==='')return null;const n=Number(String(s).replace(/[$,]/g,''));return Number.isFinite(n)&&n>=min&&n<=max?n:null;};
const enabled=(s,old)=>s===undefined?!old:['on','true','1'].includes(s)?true:['off','false','0'].includes(s)?false:null;
function release(room,p){releaseCart(room,p,true);const v=room.vehicles.find(v=>v.driver===p.id);if(v)v.driver=null;p.vehicle=null;if(p.busy){addCargo(p.cargo,p.busy.sample);p.busy=null;}p.tumble=null;p.aid=0;p.vy=0;}
function safeSpot(room,x,z){for(const r of[0,2,4,8,12])for(let n=0;n<16;n++){const nx=clamp(x+Math.cos(n*Math.PI/8)*r,-HALF+4,HALF-4),nz=clamp(z+Math.sin(n*Math.PI/8)*r,-HALF+4,HALF-4);if(canWalk(nx,nz,.5))return{x:nx,z:nz};}return{x:-25,z:58};}
function move(room,p,pos,now,remember=true){if(remember)p.consoleBack={x:p.x,y:p.y,z:p.z,yaw:p.yaw};release(room,p);const spot=p.fly?pos:safeSpot(room,pos.x,pos.z);p.x=spot.x;p.z=spot.z;p.y=Number.isFinite(pos.y)?Math.max(heightAt(p.x,p.z,room.cells),pos.y):Math.max(.3,heightAt(p.x,p.z,room.cells));if(Number.isFinite(pos.yaw))p.yaw=pos.yaw;p.immuneUntil=now+3000;return reply(`Teleported to X ${p.x.toFixed(1)}, Y ${p.y.toFixed(1)}, Z ${p.z.toFixed(1)}.`,{resync:true});}
export function runConsole(room,p,line,rules,now){
  if(typeof line!=='string'||line.length>200)return fail('Use a command up to 200 characters.');
  ensureHauling(room);
  const parts=Array.from(line.trim().matchAll(/@?"([^"]*)"|'([^']*)'|(\S+)/g),m=>m[1]??m[2]??m[3]);let command=(parts.shift()||'help').toLowerCase();const a=parts.map(s=>s.toLowerCase());let result;
  if(command==='help'){const lists=a[0]?[COMMAND_HELP[a[0]]]:Object.values(COMMAND_HELP);return lists.some(l=>!l)?fail('Help topics: travel, money, gear, info.'):reply(lists.flat());}
  if(['where','status'].includes(command))return reply([`Map: ${rules.world.size} × ${rules.world.size} m. X ${p.x.toFixed(1)}, Y ${p.y.toFixed(1)}, Z ${p.z.toFixed(1)}.`,`Crew cash $${(room.cash/100).toFixed(2)}; pouch ${(p.goldMg/1000).toFixed(3)} g.`,`Fly ${p.fly?'on':'off'}; speed ${p.speedScale||1}×; jump ${p.jumpScale||1}×; tumble protection ${p.cheatSafe?'on':'off'}.`]);
  if(command==='players')return reply(Object.values(room.players).filter(q=>q.active).map(q=>`${q.name} (${q.id}) — X ${q.x.toFixed(1)}, Z ${q.z.toFixed(1)}`));
  if(command==='equipment'){const entities=[...room.carts,...room.machines,...room.vehicles];return reply(entities.map(e=>`${e.id} · ${e.type||'wheelbarrow'} — X ${e.x.toFixed(1)}, Z ${e.z.toFixed(1)}`));}
  if(command==='marks')return reply(Object.entries(p.consoleMarks||{}).map(([name,v])=>`${name} — X ${v.x.toFixed(1)}, Y ${v.y.toFixed(1)}, Z ${v.z.toFixed(1)}`).concat('mark NAME saves your current location.'));
  if(command==='mark'){const name=a.join(' ');if(!/^[a-z][a-z0-9 _-]{0,29}$/.test(name))return fail('mark NAME: use a name beginning with a letter (max 30 characters).');if(DESTINATIONS.includes(name))return fail('That name belongs to a built-in destination.');p.consoleMarks??={};if(Object.keys(p.consoleMarks).length>=30&&!p.consoleMarks[name])return fail('You have 30 bookmarks. Reuse a name to move an existing bookmark.');p.consoleMarks[name]={x:p.x,y:p.y,z:p.z,yaw:p.yaw};result=reply(`Bookmark saved: ${name}. Use tp ${name}.`);}
  else if(command==='tp'||command==='back'){
    let pos,tag=a.join(' ');if(command==='back'){if(!p.consoleBack)return fail('No previous teleport position.');pos={...p.consoleBack};}
    else if(parts.length>=2&&number(parts[0],-HALF+4,HALF-4)!==null){const x=number(parts[0],-HALF+4,HALF-4),z=number(parts[1],-HALF+4,HALF-4),y=parts[2]===undefined?undefined:number(parts[2],0,150);if(z===null||y===null)return fail('tp X Z [Y]: X/Z must be -108..108, height 0..150.');pos={x,z,y};}
    else{const places={camp:{x:-25,z:58},shop:{x:-46,z:50},assay:{x:-37,z:63},creek:{x:riverX(40)-11,z:40},ghost:{x:riverX(-75)-11,z:-75},fox:{x:45,z:-15}};pos=places[tag]||p.consoleMarks?.[tag];const pay=/^pay([1-4])$/.exec(tag);if(pay){const d=deposits(room.seed)[Number(pay[1])-1];pos={x:d.x,z:d.z};}if(!pos){const idOrName=tag.replace(/^@/,'');const entity=[...Object.values(room.players).filter(q=>q.active),...room.carts,...room.machines,...room.vehicles].find(e=>e.id.toLowerCase()===idOrName||e.name?.toLowerCase()===idOrName);if(entity)pos={x:clamp(entity.x+3,-108,108),z:clamp(entity.z+2,-108,108)};}if(!pos)return fail('Unknown destination. Try tp camp, tp creek, tp pay1, tp X Z, or tp @"Friend Name".');}
    result=move(room,p,pos,now);
  }
  else if(['fly','noclip','land'].includes(command)){const on=command==='land'?false:enabled(a[0],p.fly);if(on===null)return fail('fly on / fly off');release(room,p);p.fly=on;if(on)p.y=Math.max(p.y,heightAt(p.x,p.z,room.cells)+2);else{const pos=safeSpot(room,p.x,p.z);p.x=pos.x;p.z=pos.z;p.y=Math.max(.3,heightAt(p.x,p.z,room.cells));p.immuneUntil=now+3000;}result=reply(on?'Flight on. WASD follows your view; Space up, Ctrl down, Shift faster.':'Flight off. Safely landed.',{resync:true});}
  else if(['speed','jump'].includes(command)){const n=number(a[0],.1,command==='speed'?10:5);if(n===null)return fail(`${command} NUMBER: 0.1–${command==='speed'?10:5}; 1 restores normal.`);p[command==='speed'?'speedScale':'jumpScale']=n;result=reply(`${command} multiplier: ${n}×.`,{resync:true});}
  else if(['safe','god'].includes(command)){const on=enabled(a[0],p.cheatSafe);if(on===null)return fail('safe on / safe off');p.cheatSafe=on;if(on){p.tumble=null;p.aid=0;}result=reply(`Tumble protection ${on?'on':'off'}.`,{resync:true});}
  else if(['recover','heal','unstuck'].includes(command)){result=move(room,p,safeSpot(room,p.x,p.z),now,false);result.lines=['Recovered and placed on safe ground.'];}
  else if(['money','cash'].includes(command)){const set=a[0]==='set',hasMode=['add','set'].includes(a[0]);if(hasMode&&parts.length!==2||!hasMode&&parts.length!==1)return fail('money AMOUNT / money add AMOUNT / money set AMOUNT');const dollars=number(parts[hasMode?1:0],0,1000000000);if(dollars===null)return fail('Use an amount between $0 and $1,000,000,000.');const cents=Math.round(dollars*100);if(!Number.isSafeInteger(room.cash+(set?0:cents)))return fail('Amount is too large.');room.cash=set?cents:room.cash+cents;result=reply(`Crew treasury: $${(room.cash/100).toFixed(2)}.`,{crewNotice:`${p.name} used the console to ${set?'set':'add'} crew cash.`});}
  else if(command==='gold'){const grams=number(parts[0],0,1000000);if(grams===null||parts.length!==1)return fail('gold GRAMS: 0–1,000,000.');p.goldMg+=grams*1000;result=reply(`Pouch: ${(p.goldMg/1000).toFixed(3)} g recovered gold.`);}
  else if(['bank','sell'].includes(command)){const amount=Math.floor(p.goldMg*rules.economy.dollarsPerGram/10);room.cash+=amount;room.totalGoldMg+=p.goldMg;p.stats.sold+=p.goldMg;p.goldMg=0;result=reply(`Sold pouch for $${(amount/100).toFixed(2)}. Crew treasury: $${(room.cash/100).toFixed(2)}.`);}
  else if(['give','unlock'].includes(command)){const ids=a[0]==='all'?rules.catalog.map(i=>i.id):[a[0]];if(ids.some(id=>!rules.catalog.some(i=>i.id===id)))return fail('Unknown equipment. Type help gear.');if(command==='give'&&a[0]!=='all'&&rules.catalog.find(i=>i.id===a[0]).kind==='vehicle')return runConsole(room,p,`spawn ${a[0]}`,rules,now);for(const id of ids){const item=rules.catalog.find(i=>i.id===id);if(!room.unlocked.includes(id))room.unlocked.push(id);if(command==='give'){if(item.kind==='personal'&&!p.upgrades.includes(id))p.upgrades.push(id);else if(item.kind==='machine'&&!p.kits.includes(id))p.kits.push(id);}}result=reply(a[0]==='all'?(command==='give'?'All upgrades, washer kits and purchase unlocks granted. Spawn vehicles separately.':'All purchase prerequisites unlocked.'):`${a[0]} ${command==='give'?'granted':'unlocked'}.`);}
  else if(command==='spawn'){const type=a[0],item=rules.catalog.find(i=>i.id===type);if(type!=='wheelbarrow'&&(!item||item.kind==='personal'))return fail('spawn wheelbarrow|rocker|sluice|washplant|excavator|truck|hydraulic');if(room.carts.length+room.machines.length+room.vehicles.length>=40)return fail('Equipment limit reached (40).');let pos=safeSpot(room,p.x-Math.sin(p.yaw)*7,p.z-Math.cos(p.yaw)*7);if(item?.kind==='machine'&&(Math.abs(pos.x-riverX(pos.z))>item.waterReach||heightAt(pos.x,pos.z,room.cells)<.65))pos=safeSpot(room,riverX(p.z)-12,clamp(p.z,-104,104));let e;
    if(type==='wheelbarrow'){e={...room.carts[0],id:`c${room.nextId++}`,...pos,cargo:emptyCargo(),operator:null,steadier:null,yaw:p.yaw,vx:0,vz:0,brake:true,tipped:false,wobble:0,roll:0,wheel:0};room.carts.push(e);}
    else if(item.kind==='machine'){e={id:`m${room.nextId++}`,type,...pos,yaw:p.yaw,cargo:emptyCargo(),goldMg:0,processed:0,running:false};room.machines.push(e);}
    else{e={id:`v${room.nextId++}`,type,...pos,yaw:p.yaw,cargo:emptyCargo(),driver:null,tipped:0,swing:0};room.vehicles.push(e);}if(item&&!room.unlocked.includes(type))room.unlocked.push(type);result=reply(`Spawned ${type}: ${e.id}, X ${e.x.toFixed(1)}, Z ${e.z.toFixed(1)}. Use tp ${e.id} to visit it.`);}
  else if(command==='fill'){if(p.busy)return fail('Cancel or finish panning first.');const e=room.vehicles.find(v=>v.id===p.vehicle)||room.carts.find(c=>c.id===p.cart),cargo=e?e.cargo:p.cargo,capacity=e?(e.type?rules.catalog.find(i=>i.id===e.type).capacity:180):p.upgrades.includes('bucket')?64:rules.player.bucketKg;const kg=parts[0]===undefined?capacity-cargo.mass:number(parts[0],0,10000),g=parts[1]===undefined?0:number(parts[1],0,10000);if(kg===null||g===null||parts.length>2)return fail('fill [KG] [GRAMS]: test gravel and contained gold.');const mass=Math.min(kg,capacity-cargo.mass);if(mass<=0)return fail('Container full. Unload first.');addCargo(cargo,{mass,goldMg:g*1000*mass/Math.max(kg,1e-8),x:p.x,z:p.z});result=reply(`Added ${mass.toFixed(1)} kg test gravel; gold stays inside it until washed.`);}
  else if(command==='time'||command==='day'){const n=number(parts[0],command==='time'?0:1,command==='time'?24:999);if(n===null||command==='day'&&!Number.isInteger(n))return fail(command==='time'?'time 0..24':'day 1..999');room[command==='time'?'clock':'day']=command==='time'?n%24:n;result=reply(`${command}: ${n}.`);}
  else if(command==='reset'){p.speedScale=p.jumpScale=1;p.fly=false;p.cheatSafe=false;result=move(room,p,safeSpot(room,p.x,p.z),now,false);result.lines=['Normal speed and jump restored. Flight and tumble protection off. Cash and equipment kept.'];}
  else return fail(`Unknown command: ${command}. Type help. No command was run.`);
  room.dirty=true;room.revision++;return result;
}

export function flyStep(pos,input,rules,scale,dt){const f=clamp(Number(input.forward)||0,-1,1),r=clamp(Number(input.right)||0,-1,1),n=Math.max(1,Math.hypot(f,r)),yaw=Number.isFinite(input.yaw)?input.yaw:pos.yaw,pitch=clamp(Number(input.pitch)||0,-1.38,1.38),speed=(input.sprint?rules.player.sprint:rules.player.speed)*1.5*(scale||1)*dt;
  pos.x=clamp(pos.x+(-Math.sin(yaw)*f*Math.cos(pitch)+Math.cos(yaw)*r)*speed/n,-HALF+3,HALF-3);pos.z=clamp(pos.z+(-Math.cos(yaw)*f*Math.cos(pitch)-Math.sin(yaw)*r)*speed/n,-HALF+3,HALF-3);pos.y=clamp(pos.y+(Math.sin(pitch)*f/n+(Number(input.vertical)||0))*speed,-10,150);pos.yaw=yaw;pos.vy=0;
}
