const {browser,player}=require('./lib2.cjs');const PORT=process.argv[2],SP=process.argv[3];
const R=[];const check=(n,ok,i)=>{R.push(ok);console.log((ok?'PASS ':'FAIL ')+n+(i?'  -- '+i:''))};
(async()=>{const b=await browser(),errs=[];const A=await player(b,PORT,'Alpha',errs),B=await player(b,PORT,'Bravo',errs);
await A.evaluate(()=>{runCommand('give gold 400');P.x=16;P.z=40.6;P.y=groundAt(P.x,P.z)});await A.waitForTimeout(500);
await A.keyboard.press('f');await A.waitForTimeout(500);check('the store opens on Me',await A.evaluate(()=>!$('#shopMe').hidden&&$('#crewShop').hidden));
await A.click('#shopModeCrew');await A.waitForTimeout(300);
const cols=await A.evaluate(()=>[...document.querySelectorAll('#crewGrid .crew-h')].map(e=>e.firstChild.textContent));
check('The crew: a column per crew member',cols.length===7&&cols.includes('Zach'),cols.join(', '));
check('a row per upgrade',await A.evaluate(()=>document.querySelectorAll('#crewGrid .crew-item').length===SIM.CREW_SHOP.length));
await A.screenshot({path:SP+'/crewshop.png'});
check('the crew start with no bucket; the Big one waits for it',/Needs Bucket/i.test(await A.evaluate(()=>$('.crew-buy[data-key="Zach|bucket2"]').textContent)),await A.evaluate(()=>$('.crew-buy[data-key="Zach|bucket2"]').textContent));
const g0=await A.evaluate(()=>S.seeds);
await A.click('.crew-buy[data-key="Zach|bucket"]');await A.waitForTimeout(150);
check('first click asks "Sure?"',/Sure/.test(await A.evaluate(()=>$('.crew-buy[data-key="Zach|bucket"]').textContent))&&await A.evaluate(g=>S.seeds===g,g0));
await A.click('.crew-buy[data-key="Zach|bucket"]');await A.waitForTimeout(800);
check('second click buys it from your gold',await A.evaluate(g=>S.seeds===g-30,g0),`${g0} -> ${await A.evaluate(()=>S.seeds)}`);
check('Zach carries a bucket now (5 holes) (your screen)',await A.evaluate(()=>crewBucketMax(bots.find(b=>b.d.n==='Zach'))===5));
check('...and your friend\'s',await B.evaluate(()=>crewBucketMax(bots.find(b=>b.d.n==='Zach'))===5));
check('your friend is told',/Alpha bought Zach a bucket/.test(await B.evaluate(()=>[...document.querySelectorAll('#toasts > *')].map(e=>e.textContent).join('|'))));
check('the row shows he has it',/Has it/.test(await A.evaluate(()=>$('.crew-buy[data-key="Zach|bucket"]').textContent)));
// a spade digs faster
const rate=await A.evaluate(()=>new Promise(res=>{const z=bots.find(b=>b.d.n==='Stan');z.hole=addHole({x:-30,z:-20,d:0.1,bot:true});z.state='dig';z.p.g.position.set(-30,groundAt(-30,-20),-20);const d0=z.hole.d;setTimeout(()=>res(z.hole.d-d0),10000)}));
await A.evaluate(()=>{crewMsg({up:Object.assign({},CREW_UP,{Stan:{spade:true}})})});
const rate2=await A.evaluate(()=>new Promise(res=>{const z=bots.find(b=>b.d.n==='Stan');z.hole=addHole({x:-34,z:-20,d:0.1,bot:true});z.state='dig';z.p.g.position.set(-34,groundAt(-34,-20),-20);const d0=z.hole.d;setTimeout(()=>res(z.hole.d-d0),10000)}));
check('a sharpened spade: he digs ~60% faster',rate2>rate*1.35,`${rate.toFixed(2)} m -> ${rate2.toFixed(2)} m in 10 s`);
// both buy the same thing at once: one pays, the other gets their gold back
await B.evaluate(()=>{runCommand('give gold 400')});const a1=await A.evaluate(()=>S.seeds),b1=await B.evaluate(()=>S.seeds);
await Promise.all([A.evaluate(()=>crewBuy('Larry',SIM.CREW_SHOP.find(i=>i.id==='canteen'))),B.evaluate(()=>{shopOpen=true;crewBuy('Larry',SIM.CREW_SHOP.find(i=>i.id==='canteen'))})]);
await A.waitForTimeout(1200);const spent=(a1-await A.evaluate(()=>S.seeds))+(b1-await B.evaluate(()=>S.seeds));
check('two of you buying the same thing: only one pays',spent===35,`spent ${spent} between you`);
console.log(R.filter(Boolean).length+'/'+R.length+' passed | errors:',errs.join(' | ')||'none');await b.close();process.exit(R.every(Boolean)&&!errs.length?0:1)})();
