import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRoom,createPlayer,act,tick,addCargo} from '../shared/simulation.mjs';import {tickAutomation,feederPose} from '../shared/automation.mjs';import {emptyCargo} from '../shared/cargo.mjs';import {heightAt,riverX} from '../shared/world.mjs';import {spillCart,releaseCart} from '../shared/hauling.mjs';import {exportWorld} from '../shared/export.mjs';
const rules=JSON.parse(fs.readFileSync(new URL('../shared/rules.json',import.meta.url)));
function setup(){const r=createRoom('AUTOTEST',rules),p=createPlayer('auto-miner','Solo',r),x=riverX(30)-12,z=30;Object.assign(p,{x:x+2,z,y:heightAt(x+2,z),input:{},lastInput:1000});const m={id:'belt',type:'feeder',x,z,yaw:0,cargo:emptyCargo(),goldMg:0,processed:0},w={id:'washer',type:'sluice',x,z:z-4.4,yaw:0,cargo:emptyCargo(),goldMg:0,processed:0};r.machines.push(m,w);return {r,p,m,w};}
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const unwashed=r=>r.machines.reduce((n,m)=>n+m.cargo.mass,0)+r.spills.reduce((n,s)=>n+s.cargo.mass,0)+r.clods.reduce((n,c)=>n+c.cargo.mass,0)+Object.values(r.players).reduce((n,p)=>n+p.cargo.mass,0);
function step(r,n,dt=.05,start=1000){for(let i=0;i<n;i++)tick(r,rules,dt,start+i*dt*1000);}
test('new automation purchases require earned progression and motor fits exactly one existing rocker',()=>{const{r,p}=setup();r.machines=[];Object.assign(p,{x:-46,z:44});r.cash=1e8;assert.equal(act(r,p,{type:'buy',item:'feeder'},rules,1000).ok,false);assert.equal(act(r,p,{type:'buy',item:'rockerdrive'},rules,1000).ok,false);assert.equal(act(r,p,{type:'buy',item:'rocker'},rules,1000).ok,true);assert.equal(act(r,p,{type:'buy',item:'rockerdrive'},rules,1000).ok,true);Object.assign(p,{x:riverX(30)-12,z:30});assert.equal(act(r,p,{type:'deploy',item:'rockerdrive',x:p.x,z:p.z},rules,1000).ok,false);assert.ok(p.kits.includes('rockerdrive'));assert.equal(act(r,p,{type:'deploy',item:'rocker',x:p.x,z:p.z},rules,1000).ok,true);assert.equal(act(r,p,{type:'deploy',item:'rockerdrive',x:p.x,z:p.z},rules,1000).ok,true);assert.equal(r.machines[0].powered,true);assert.equal(act(r,p,{type:'deploy',item:'rockerdrive',x:p.x,z:p.z},rules,1001).ok,false);assert.equal(r.machines.length,1);assert.equal(act(r,p,{type:'pack',target:r.machines[0].id},rules,1100).ok,true);assert.ok(p.kits.includes('rockerdrive'));});
test('motor removes the hand-rocking job for a solo player and persists in engine export',()=>{const{r,p,w}=setup();r.machines=[w];w.type='rocker';addCargo(w.cargo,{mass:14,goldMg:100,x:w.x,z:w.z});step(r,30);close(w.cargo.mass,14);w.powered=true;step(r,100);close(w.cargo.mass,0);close(w.goldMg,90);assert.equal(exportWorld(r).machines[0].powered,true);});
test('feeder picks up real loose piles, outputs physical parcels and autonomously washes conserved gold',()=>{const{r,m,w}=setup();r.spills.push({id:'pile',x:m.x,z:m.z,cargo:{mass:60,goldMg:600,x:m.x,z:m.z}});step(r,600);close(r.spills.length,0);close(r.clods.length,0);close(m.cargo.mass,0);close(w.cargo.mass,0);close(m.processed,60);close(w.goldMg,564);close(unwashed(r)+w.processed,60);assert.equal(m.jammed,undefined);});
test('wrongly aimed belt causes a real recoverable output pile, backs up, and can be cleared solo',()=>{const{r,p,m,w}=setup();w.x+=10;addCargo(m.cargo,{mass:90,goldMg:900,x:m.x,z:m.z});step(r,440);assert.equal(m.jammed,true);assert.equal(m.jamReason,'backed-up chute');close(unwashed(r),90);close(w.goldMg,0);const out=feederPose(m,r.cells).outlet;assert.ok(r.spills.some(s=>Math.hypot(s.x-out.x,s.z-out.z)<1.5));Object.assign(p,{x:m.x+1.8,z:m.z,y:heightAt(m.x+1.8,m.z)});let burped=false;for(let i=0;i<45;i++){p.lastInput=23000+i*50;p.input={help:true};const e=tick(r,rules,.05,p.lastInput);if(e.some(e=>e.effect?.type==='beltBurp'))burped=true;}assert.equal(burped,true);assert.ok(r.clods.length>0);close(unwashed(r),90);assert.ok(r.clods.every(c=>Number.isFinite(c.vx)));});
test('overloading produces a predictable jam; distant or stale help cannot clear it; a friend can',()=>{const{r,p,m}=setup();addCargo(m.cargo,{mass:180,goldMg:500,x:m.x,z:m.z});step(r,110);assert.equal(m.jammed,true);assert.equal(m.jamReason,'overloaded hopper');p.input={help:true};p.lastInput=0;step(r,50,.05,10000);assert.equal(m.jammed,true);const q=createPlayer('auto-friend','Friend',r);Object.assign(q,{x:m.x+2,z:m.z,y:heightAt(m.x+2,m.z)});for(let i=0;i<41;i++){q.lastInput=14000+i*50;q.input={help:true};tick(r,rules,.05,q.lastInput);}assert.equal(m.jammed,false);assert.equal(m.helper,q.id);close(unwashed(r)+r.machines[1].processed,180);});
test('full downstream washer and clod ceiling pause transfer without deleting or minting paydirt',()=>{const{r,m,w}=setup();addCargo(m.cargo,{mass:30,goldMg:50,x:m.x,z:m.z});addCargo(w.cargo,{mass:320,goldMg:0,x:w.x,z:w.z});for(let i=0;i<20;i++)tickAutomation(r,rules,.05,1000+i*50);close(m.cargo.mass,30);assert.equal(m.running,false);w.cargo=emptyCargo();r.clods=Array.from({length:144},(_,i)=>({id:'d'+i,cargo:emptyCargo()}));for(let i=0;i<20;i++)tickAutomation(r,rules,.05,3000+i*50);close(m.cargo.mass,30);});
test('a nearby helper catches an unheld runaway barrow and parks it without stealing its cargo',()=>{const{r,p}=setup();r.machines=[];const c=r.carts[0];Object.assign(c,{x:p.x,z:p.z,brake:false,vx:3,vz:0});addCargo(c.cargo,{mass:60,goldMg:50,x:c.x,z:c.z});Object.assign(p,{x:c.x-1.8,z:c.z,y:heightAt(c.x-1.8,c.z)});let caught=false;for(let i=0;i<20;i++){p.lastInput=1000+i*50;p.input={help:true};const e=tick(r,rules,.05,p.lastInput);if(e.some(e=>e.broadcast?.includes('caught the runaway')))caught=true;}assert.equal(caught,true);assert.equal(c.brake,true);assert.equal(c.operator,null);close(c.cargo.mass,60);close(c.cargo.goldMg,50);});
