import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRoom,createPlayer,act,tick,snapshot,addCargo} from '../shared/simulation.mjs';import {tumble} from '../shared/hauling.mjs';import {canWalk,heightAt,nearWater} from '../shared/world.mjs';
const rules=JSON.parse(fs.readFileSync(new URL('../shared/rules.json',import.meta.url)));
function setup(){const r=createRoom('CONTEST',rules),p=createPlayer('console-miner-123456','Dusty',r);return{r,p,cmd:line=>act(r,p,{type:'console',line},rules,1000)};}
test('console rejects invalid amounts, out-of-map teleports and code without mutating the world',()=>{const{r,p,cmd}=setup();for(const line of['money -1','money Infinity','money set NaN','money set 100 extra','gold -1','speed 1000','jump NaN','tp 999 999','fly banana','globalThis.process.exit()','spawn mystery']){const before=JSON.stringify(r);assert.equal(cmd(line).ok,false,line);assert.equal(JSON.stringify(r),before,line);}assert.equal(p.active,true);});
test('money commands use integer cents and synchronize crew cash; gold banks at the normal rate',()=>{const{r,p,cmd}=setup();const q=createPlayer('console-friend-123456','Friend',r);assert.equal(cmd('money $1,234.56').ok,true);assert.equal(r.cash,123456);cmd('money add 0.15');assert.equal(r.cash,123471);cmd('money set 200');assert.equal(snapshot(r,q,rules,1000).cash,20000);cmd('gold 2.5');assert.equal(p.goldMg,2500);cmd('bank');assert.equal(p.goldMg,0);assert.equal(r.cash,27500);assert.equal(r.totalGoldMg,2500);});
test('teleports return a pending pan parcel, release equipment and place the player on valid ground',()=>{const{r,p,cmd}=setup();p.busy={sample:{mass:8,goldMg:124,x:1,z:2}};p.tumble={until:2000,vx:0,vz:0};assert.equal(cmd('tp shop').ok,true);assert.equal(p.busy,null);assert.equal(p.tumble,null);assert.equal(p.cargo.goldMg,124);assert.equal(p.cargo.mass,8);assert.ok(canWalk(p.x,p.z));const c=r.carts[0];p.x=c.x;p.z=c.z;act(r,p,{type:'cart',target:c.id},rules,1001);cmd('tp creek');assert.equal(p.cart,null);assert.equal(c.operator,null);assert.equal(c.brake,true);assert.equal(cmd('tp -37 69').ok,true);assert.ok(canWalk(p.x,p.z));assert.equal(p.y,Math.max(.3,heightAt(p.x,p.z,r.cells)));});
test('bookmarks, back, geological destinations and quoted friend names work',()=>{const{r,p,cmd}=setup();cmd('mark home');cmd('tp pay1');const x=p.x,z=p.z;cmd('mark "rich claim"');cmd('tp home');assert.equal(p.x,-25);cmd('back');assert.equal(p.x,x);assert.equal(p.z,z);cmd('tp "rich claim"');assert.equal(p.x,x);const q=createPlayer('named-friend-123456','Pickaxe Pete',r);q.x=50;q.z=-10;assert.equal(cmd('tp @"Pickaxe Pete"').ok,true);assert.equal(p.x,53);assert.equal(p.z,-8);});
test('flight traverses buildings, follows pitch, supports vertical movement and safely lands',()=>{const{r,p,cmd}=setup();cmd('tp -37 77');cmd('fly on');p.input={forward:1,yaw:0,pitch:0};for(let n=0;n<40;n++){p.lastInput=1000+n*50;tick(r,rules,.05,p.lastInput);}assert.ok(p.z<67);const y=p.y;p.input={vertical:1,yaw:0};p.lastInput=3100;tick(r,rules,.1,3100);assert.ok(p.y>y);cmd('fly off');assert.equal(p.fly,false);assert.ok(canWalk(p.x,p.z));assert.equal(p.y,Math.max(.3,heightAt(p.x,p.z,r.cells)));});
test('speed multiplier changes real walking; reset removes flight and tumble protection without deleting cash',()=>{function distance(scale){const{r,p,cmd}=setup();cmd(`speed ${scale}`);const x=p.x;p.input={forward:1,yaw:-Math.PI/2};p.lastInput=1000;tick(r,rules,.1,1000);return p.x-x;}assert.ok(Math.abs(distance(3)/distance(1)-3)<1e-8);const{r,p,cmd}=setup();cmd('money 100');cmd('god on');tumble(r,p,5000);assert.equal(p.tumble,null);cmd('fly on');cmd('speed 4');cmd('jump 3');cmd('reset');assert.equal(p.fly,false);assert.equal(p.cheatSafe,false);assert.equal(p.speedScale,1);assert.equal(p.jumpScale,1);assert.equal(r.cash,10000);});
test('gear commands grant useful kits, spawn equipment, preserve limits and respect container capacity',()=>{const{r,p,cmd}=setup();cmd('give all');assert.equal(p.upgrades.length,rules.catalog.filter(i=>i.kind==='personal').length);assert.equal(p.kits.length,rules.catalog.filter(i=>i.kind==='machine'||i.kind==='mine').reduce((n,i)=>n+(i.bundle||1),0));assert.equal(p.kits.filter(k=>k==='minetrack').length,6);assert.equal(r.unlocked.length,rules.catalog.length);cmd('spawn washplant');const plant=r.machines[0];assert.ok(nearWater(plant.x,plant.z,32));cmd('spawn truck');const truck=r.vehicles[0];cmd('tp '+truck.id);act(r,p,{type:'enter',target:truck.id},rules,1001);cmd('fill 5000 20');assert.equal(truck.cargo.mass,2400);assert.equal(truck.cargo.goldMg,9600);assert.equal(snapshot(r,p,rules,1000).vehicles[0].cargo.goldMg,undefined);cmd('recover');cmd('spawn wheelbarrow');assert.equal(r.carts.length,2);while(r.vehicles.length+r.carts.length+r.machines.length<40)cmd('spawn truck');const before=JSON.stringify(r);assert.equal(cmd('give hydraulic').ok,false);assert.equal(JSON.stringify(r),before);});

