import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRoom,createPlayer,act,tick,snapshot,addCargo} from '../shared/simulation.mjs';
import {ensureArm,armTargets,tickArm,excavatorPose,ARM} from '../shared/excavator.mjs';
import {heightAt} from '../shared/world.mjs';import {tickSoil} from '../shared/soil.mjs';
const rules=JSON.parse(fs.readFileSync(new URL('../shared/rules.json',import.meta.url)));
function setup(){const r=createRoom('ARMTEST',rules,'sandbox'),p=createPlayer('arm-player','Solo',r),v=r.vehicles[0];Object.assign(v,{x:80,z:60,yaw:0});Object.assign(p,{x:80,z:60,y:heightAt(80,60)});assert.equal(act(r,p,{type:'enter',target:v.id},rules,1000).ok,true);ensureArm(v);return {r,p,v};}
function contact(r,v){const a=ensureArm(v);a.curl=0;a.stick=1.3;let best=1e6,bestBoom=0;for(let b=-.2;b<1.05;b+=.005){a.boom=b;const t=excavatorPose(v,r.cells).tip,d=Math.abs(t.y-heightAt(t.x,t.z,r.cells)-.1);if(d<best){best=d;bestBoom=b;}}a.boom=bestBoom;a.target={boom:a.boom,stick:a.stick,slew:a.slew,curl:0};return excavatorPose(v,r.cells).tip;}
const total=r=>r.vehicles.reduce((n,v)=>n+v.cargo.mass,0)+r.clods.reduce((n,c)=>n+c.cargo.mass,0)+r.spills.reduce((n,s)=>n+s.cargo.mass,0);
test('shared arm targets reject nonfinite inputs and every spring joint stays bounded under extreme control',()=>{const {v}=setup(),t=armTargets({boom:Infinity,slew:999,stick:-999,curl:NaN});assert.equal(t.slew,2.5);assert.equal(t.stick,.45);assert.equal(t.curl,0);for(let i=0;i<200;i++)tickArm(v,{arm:{boom:i%2?10:-10,stick:10,slew:-10,curl:10}},.05);for(const k of Object.keys(t))assert.ok(v.arm[k]>=ARM[k][0]&&v.arm[k]<=ARM[k][1]);assert.ok(Object.values(v.arm.velocity).every(Number.isFinite));});
test('mouse-equivalent joint targets change the real bucket position, with lag and settling rather than a canned swing',()=>{const{r,v}=setup(),before=excavatorPose(v,r.cells);tickArm(v,{arm:{...v.arm.target,slew:1,boom:.7,stick:.7}},.05);assert.ok(v.arm.slew>0&&v.arm.slew<1);for(let i=0;i<100;i++)tickArm(v,null,.05);const after=excavatorPose(v,r.cells);assert.ok(Math.hypot(before.tip.x-after.tip.x,before.tip.z-after.tip.z)>3);assert.ok(after.tip.y>before.tip.y);assert.ok(Math.abs(v.arm.slew-1)<.01);});
test('actual teeth contact and deliberate pull dig only that patch and load conserved material once',()=>{const{r,p,v}=setup(),point=contact(r,v);assert.equal(act(r,p,{type:'excavatorPlant',x:0,z:0},rules,1000).ok,true);assert.equal(act(r,p,{type:'excavatorScoop',pull:10},rules,1300).ok,false);assert.equal(r.totalDugKg,0);const result=act(r,p,{type:'excavatorScoop',pull:40},rules,1300);assert.equal(result.ok,true,result.message);assert.equal(v.cargo.mass,180);assert.equal(r.totalDugKg,180);assert.ok(r.cells[Object.keys(r.cells)[0]]);assert.equal(result.effect.x,point.x);assert.equal(act(r,p,{type:'excavatorScoop',pull:40},rules,1400).ok,false);assert.equal(v.cargo.mass,180);});
test('ownership, protected ground, full bucket, raised teeth and moved-away plants reject cuts without mutation',()=>{const{r,p,v}=setup(),q=createPlayer('friend','Friend',r);assert.equal(act(r,q,{type:'excavatorPlant'},rules,1000).ok,false);v.arm.boom=1;assert.equal(act(r,p,{type:'excavatorPlant'},rules,1000).ok,false);contact(r,v);v.cargo.mass=720;assert.equal(act(r,p,{type:'excavatorPlant'},rules,1000).ok,false);v.cargo.mass=0;assert.equal(act(r,p,{type:'excavatorPlant'},rules,1000).ok,true);v.x+=8;assert.equal(act(r,p,{type:'excavatorScoop',pull:40},rules,1300).ok,false);assert.equal(r.totalDugKg,0);v.x=-37;v.z=60;contact(r,v);assert.equal(act(r,p,{type:'excavatorPlant'},rules,2000).ok,false);assert.equal(Object.keys(r.cells).length,0);});
test('dumping over an actual truck bed catches falling dirt with all gold; a miss becomes recoverable piles',()=>{for(const catchIt of[true,false]){const{r,p,v}=setup(),truck=r.vehicles[1];Object.assign(v.arm,{boom:.9,stick:1.3,curl:1});addCargo(v.cargo,{mass:360,goldMg:321,x:80,z:60});const tip=excavatorPose(v,r.cells).tip;Object.assign(truck,{x:catchIt?tip.x:10,z:catchIt?tip.z-1.1:90,yaw:0});assert.equal(act(r,p,{type:'excavatorDump',power:0},rules,2000).ok,true);assert.equal(v.cargo.mass,0);assert.equal(r.clods.length,6);for(let i=0;i<180;i++)tickSoil(r,rules,.05,2050+i*50);assert.ok(Math.abs(total(r)-360)<1e-6);const gold=r.vehicles.reduce((n,v)=>n+v.cargo.goldMg,0)+r.spills.reduce((n,s)=>n+s.cargo.goldMg,0);assert.ok(Math.abs(gold-321)<1e-6);if(catchIt)assert.equal(truck.cargo.mass,360);else assert.ok(r.spills.length>0);}});
test('flick impulse flings bounded parcels; malformed dumps and full receivers never delete material',()=>{const{r,p,v}=setup();addCargo(v.cargo,{mass:720,goldMg:999,x:80,z:60});assert.equal(act(r,p,{type:'excavatorDump',power:NaN},rules,2000).ok,false);assert.equal(v.cargo.mass,720);v.arm.slew=.6;v.arm.velocity.slew=1.5;assert.equal(act(r,p,{type:'excavatorDump',power:1},rules,2000).ok,true);assert.equal(r.clods.length,12);assert.ok(r.clods.some(c=>Math.hypot(c.vx,c.vz)>10));for(let i=0;i<200;i++)tickSoil(r,rules,.05,2050+i*50);assert.ok(Math.abs(total(r)-720)<1e-6);});
test('fresh input drives joints in the real tick; stale input, exit and JSON reload retain load without ghost scoops',()=>{const{r,p,v}=setup();p.lastInput=2000;p.input={arm:{...v.arm.target,boom:.7,slew:.8}};tick(r,rules,.2,2000);assert.ok(v.arm.slew>0);addCargo(v.cargo,{mass:180,goldMg:123,x:80,z:60});p.input.arm.slew=-2;tick(r,rules,.2,3000);assert.equal(v.arm.target.slew,.8);const copy=JSON.parse(JSON.stringify(r));assert.equal(copy.vehicles[0].cargo.mass,180);assert.equal(copy.vehicles[0].arm.target.slew,.8);assert.equal(snapshot(r,p,rules,3000).vehicles[0].arm.target.slew,.8);act(r,p,{type:'enter'},rules,3100);assert.equal(v.driver,null);assert.equal(v.cargo.mass,180);assert.equal(act(r,p,{type:'excavatorScoop',pull:40},rules,3200).ok,false);});
test('excavator E transfer into a washer acknowledges the conserved load',()=>{const{r,p,v}=setup(),m={id:'washer-test',type:'sluice',x:v.x+1,z:v.z,cargo:{mass:0,goldMg:0,x:0,z:0},goldMg:0};r.machines.push(m);addCargo(v.cargo,{mass:180,goldMg:123,x:v.x,z:v.z});const result=act(r,p,{type:'interact',target:m.id},rules,2000);assert.equal(result.ok,true,result.message);assert.equal(v.cargo.mass,0);assert.equal(m.cargo.mass,180);assert.equal(m.cargo.goldMg,123);assert.match(result.message,/Loaded 180/);});
