import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';import WebSocket from 'ws';
import {excavatorPose} from '../shared/excavator.mjs';import {heightAt} from '../shared/world.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,limit=7000){const t=Date.now();while(Date.now()-t<limit){if(await fn())return;await pause(35);}throw Error('Arm network timeout');}
test('real host acknowledges bucket planting, replicates eight-client joint motion and cuts, and restores a loaded arm',{timeout:35000},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gold-arm-host-')),sockets=[];let host;
 const port=await new Promise(resolve=>{const n=net.createServer();n.listen(0,'127.0.0.1',()=>{const p=n.address().port;n.close(()=>resolve(p));});}),origin=`http://127.0.0.1:${port}`;
 async function start(){host=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),GOLD_FEVER_SAVE_DIR:path.join(dir,'worlds'),GOLD_FEVER_CONTROL_DIR:path.join(dir,'control')},stdio:'ignore',windowsHide:true});await until(async()=>{try{return(await fetch(origin+'/api/health')).ok;}catch{return false;}});}
 async function stop(){await fetch(origin+'/api/host/stop',{method:'POST',headers:{Authorization:`Bearer ${fs.readFileSync(path.join(dir,'control/host.key'),'utf8')}`}});await until(()=>host.exitCode!==null);}
 async function join(token=randomUUID()){const ws=new WebSocket(`ws://127.0.0.1:${port}/crew`),c={ws,state:null,results:[],patches:0};sockets.push(ws);ws.on('message',raw=>{const m=JSON.parse(raw);if(m.type==='welcome')c.state=m.state;if(m.type==='snapshot')c.state=m;if(m.type==='result')c.results.push(m);if(m.type==='terrain')c.patches+=m.patches.length;});await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});ws.send(JSON.stringify({type:'join',token,room:'ARMHOST',name:'Arm crew',crewSize:8}));await until(()=>c.state);return c;}
 async function action(c,a){const n=c.results.length;c.ws.send(JSON.stringify({type:'action',action:a}));await until(()=>c.results.length>n);return c.results.at(-1);}
 try{await start();const token=randomUUID(),a=await join(token),friends=[];for(let i=0;i<7;i++)friends.push(await join());await until(()=>a.state.players.length===8);
  assert.equal((await action(a,{type:'console',line:'tp 55 2'})).ok,true);a.ws.send(JSON.stringify({type:'input',yaw:0}));await pause(80);assert.equal((await action(a,{type:'console',line:'spawn excavator'})).ok,true);await until(()=>a.state.vehicles.length===1);const id=a.state.vehicles[0].id;
  await action(a,{type:'console',line:'tp '+id});assert.equal((await action(a,{type:'enter',target:id})).ok,true);await until(()=>a.state.self.vehicle===id);
  let best=Infinity,boom=0;for(let b=-.2;b<1.05;b+=.005){const v={...a.state.vehicles[0],arm:{boom:b,stick:1.3,slew:.35,curl:0}},t=excavatorPose(v).tip,d=Math.abs(t.y-heightAt(t.x,t.z)-.1);if(d<best){best=d;boom=b;}}
  a.ws.send(JSON.stringify({type:'input',arm:{boom,stick:1.3,slew:.35,curl:0}}));await until(()=>Math.abs(a.state.vehicles[0].arm.boom-boom)<.01&&friends.every(c=>Math.abs(c.state.vehicles[0].arm.slew-.35)<.01));
  const planted=await action(a,{type:'excavatorPlant'});assert.equal(planted.ok,true,planted.message);assert.equal(planted.excavator,'planted');await pause(220);const loaded=await action(a,{type:'excavatorScoop',pull:40});assert.equal(loaded.ok,true,loaded.message);assert.equal(loaded.excavator,'loaded');await until(()=>friends.every(c=>c.state.vehicles[0].cargo.mass===180&&c.patches===9));
  await stop();const saved=JSON.parse(fs.readFileSync(path.join(dir,'worlds/ARMHOST.json')));assert.equal(saved.vehicles[0].cargo.mass,180);assert.equal(saved.vehicles[0].driver,null);assert.equal(Object.values(saved.players)[0].excavatorPlant,null);
  await start();const restored=await join(token);assert.equal(restored.state.self.vehicle,null);assert.equal(restored.state.vehicles[0].cargo.mass,180);assert.ok(Math.abs(restored.state.vehicles[0].arm.target.slew-.35)<.001);assert.equal(restored.state.vehicles[0].driver,null);await stop();
 }finally{for(const s of sockets)s.terminate();if(host?.exitCode===null)host.kill();const resolved=path.resolve(dir);if(path.dirname(resolved)===path.resolve(os.tmpdir())&&path.basename(resolved).startsWith('gold-arm-host-'))fs.rmSync(resolved,{recursive:true,force:true});}
});
