import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';import WebSocket from 'ws';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){const t=Date.now();while(Date.now()-t<7000){if(await fn())return;await pause(35);}throw Error('Guard network timeout');}
test('eight real sockets share four guards, an attack and conserved spill; restart preserves the roster without a stale attack',{timeout:30000},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gold-guards-host-')),sockets=[];let host;
 const port=await new Promise(resolve=>{const n=net.createServer();n.listen(0,'127.0.0.1',()=>{const p=n.address().port;n.close(()=>resolve(p));});}),origin=`http://127.0.0.1:${port}`;
 async function start(){host=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),GOLD_FEVER_SAVE_DIR:path.join(dir,'worlds'),GOLD_FEVER_CONTROL_DIR:path.join(dir,'control')},stdio:'ignore',windowsHide:true});await until(async()=>{try{return(await fetch(origin+'/api/health')).ok;}catch{return false;}});}
 async function stop(){await fetch(origin+'/api/host/stop',{method:'POST',headers:{Authorization:`Bearer ${fs.readFileSync(path.join(dir,'control/host.key'),'utf8')}`}});await until(()=>host.exitCode!==null);}
 async function join(token=randomUUID()){const ws=new WebSocket(`ws://127.0.0.1:${port}/crew`),c={ws,state:null,results:[],dancers:new Set()};sockets.push(ws);ws.on('message',raw=>{const m=JSON.parse(raw);if(m.type==='welcome')c.state=m.state;if(m.type==='snapshot')c.state=m;if(m.type==='result')c.results.push(m);for(const g of c.state?.guards||[])if(g.state==='dance')c.dancers.add(g.target);});await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});ws.send(JSON.stringify({type:'join',token,room:'GUARDHOST',name:'Guard crew',crewSize:8}));await until(()=>c.state);return c;}
 async function action(c,a){const n=c.results.length;c.ws.send(JSON.stringify({type:'action',action:a}));await until(()=>c.results.length>n);return c.results.at(-1);}
 try{await start();const token=randomUUID(),a=await join(token),friends=[];for(let i=0;i<7;i++)friends.push(await join());await until(()=>a.state.players.length===8);const id=a.state.self.id;
  assert.ok([a,...friends].every(c=>c.state.guards.length===4));await action(a,{type:'console',line:'fill 24 1'});await action(a,{type:'console',line:'tp 28 -40 9.15'});
  await until(()=>[a,...friends].every(c=>c.dancers.has(id)));await until(()=>a.state.self.guardSafeUntil>0&&a.state.self.cargo.mass<24);await until(()=>friends.every(c=>c.state.spills.some(s=>s.cargo.mass>0)));
  await action(a,{type:'console',line:'tp camp'});await stop();const saved=JSON.parse(fs.readFileSync(path.join(dir,'worlds/GUARDHOST.json'))),p=Object.values(saved.players).find(p=>p.id===id);
  assert.equal(saved.guards.length,4);assert.equal(new Set(saved.guards.map(g=>g.id)).size,4);assert.ok(Math.abs(p.cargo.mass+saved.spills.reduce((n,s)=>n+s.cargo.mass,0)-24)<1e-6);assert.ok(Math.abs(p.cargo.goldMg+saved.spills.reduce((n,s)=>n+s.cargo.goldMg,0)-1000)<1e-6);
  await start();const restored=await join(token);assert.equal(restored.state.guards.length,4);assert.equal(restored.state.self.guardKnock,null);assert.equal(restored.state.self.guardSafeUntil,0);assert.equal(restored.state.self.cargo.mass,p.cargo.mass);assert.ok(restored.state.guards.every(g=>g.state==='patrol'&&g.target===null));await stop();
 }finally{for(const s of sockets)s.terminate();if(host?.exitCode===null)host.kill();const resolved=path.resolve(dir);if(path.dirname(resolved)===path.resolve(os.tmpdir())&&path.basename(resolved).startsWith('gold-guards-host-'))fs.rmSync(resolved,{recursive:true,force:true});}
});
