import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {randomUUID,createHash} from 'node:crypto';import WebSocket from 'ws';
import {FOREST_TREES,heightAt} from '../shared/world.mjs';
import {createRoom,createPlayer,act,addCargo} from '../shared/simulation.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),rules=JSON.parse(fs.readFileSync(path.join(root,'shared/rules.json'))),pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,time=8000){const start=Date.now();while(Date.now()-start<time){if(await fn())return;await pause(40);}throw Error('Timed out waiting for mine network state');}
test('eight clients share mine cuts; a solo miner recovers a loaded hoist after a mid-shaft host restart',{timeout:35000},async()=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gold-mine-host-'));fs.mkdirSync(path.join(dir,'worlds'));
  const token=randomUUID(),hash=createHash('sha256').update(token).digest('hex'),room=createRoom('MINEHOST',rules,'rush',8),p=createPlayer(hash,'Solo hoister',room);p.x=-68;p.z=30;p.y=-6;p.yaw=Math.PI/2;
  const tree=FOREST_TREES[0];Object.assign(p,{x:tree.x,y:heightAt(tree.x,tree.z),z:tree.z+2,yaw:0});for(let i=0;i<5;i++)assert.equal(act(room,p,{type:'chopTree',target:tree.id,yaw:0,pitch:0},rules,1000+i*700).ok,true);assert.equal(act(room,p,{type:'collectWood',target:tree.id},rules,6000).ok,true);assert.equal(act(room,p,{type:'craftSupport'},rules,6100).ok,true);Object.assign(p,{x:-68,y:-6,z:30,yaw:Math.PI/2});assert.equal(act(room,p,{type:'deploy',item:'timber',x:-70,y:-6,z:30,yaw:Math.PI/2},rules,6200).ok,true);room.mine.rubble.push({id:'saved-fall',x:-70,y:-6,z:26,yaw:0,radius:1.45,height:2.25,remaining:36,total:36});room.mine.terrainRevision++;
  for(const item of ['minetrack','minecart','hoist','steamhoist']){p.kits.push(item);const r=act(room,p,{type:'deploy',item,x:-68,y:-6,z:30,yaw:-Math.PI/2},rules,1000);assert.equal(r.ok,true,r.message);}
  p.upgrades=['minerpick','mattock','tunnelpick'];const cart=room.mine.carts[0];addCargo(cart.cargo,{mass:100,goldMg:345.67,x:-70,z:30});fs.writeFileSync(path.join(dir,'worlds/MINEHOST.json'),JSON.stringify(room));
  const legacyToken=randomUUID(),legacy=createRoom('OLDMINE',rules),legacyPlayer=createPlayer(createHash('sha256').update(legacyToken).digest('hex'),'Old surface miner',legacy);delete legacy.mine;legacyPlayer.x=-74;legacyPlayer.z=20;legacyPlayer.y=3.15;fs.writeFileSync(path.join(dir,'worlds/OLDMINE.json'),JSON.stringify(legacy));
  const port=await new Promise(resolve=>{const n=net.createServer();n.listen(0,'127.0.0.1',()=>{const p=n.address().port;n.close(()=>resolve(p));});}),origin=`http://127.0.0.1:${port}`,sockets=[];let host;
  async function start(){host=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),GOLD_FEVER_SAVE_DIR:path.join(dir,'worlds'),GOLD_FEVER_CONTROL_DIR:path.join(dir,'control')},stdio:'ignore',windowsHide:true});await until(async()=>{try{return(await fetch(origin+'/api/health')).ok;}catch{return false;}});}
  async function stop(){await fetch(origin+'/api/host/stop',{method:'POST',headers:{Authorization:`Bearer ${fs.readFileSync(path.join(dir,'control/host.key'),'utf8')}`}});await until(()=>host.exitCode!==null);}
  async function join(pass=randomUUID(),code='MINEHOST'){const ws=new WebSocket(`ws://127.0.0.1:${port}/crew`),c={ws,latest:null,welcome:null,patches:[]};sockets.push(ws);ws.on('message',raw=>{const m=JSON.parse(raw);if(m.type==='welcome'){c.welcome=m;c.latest=m.state;}if(m.type==='snapshot')c.latest=m;if(m.type==='mineBrushes')c.patches.push(...m.brushes);});await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});ws.send(JSON.stringify({type:'join',room:code,token:pass,name:'Mine crew'}));await until(()=>c.welcome);return c;}
  const action=(c,a)=>c.ws.send(JSON.stringify({type:'action',action:a}));
  try{
    await start();const migrated=await join(legacyToken,'OLDMINE');assert.equal(migrated.latest.self.y,6);assert.equal(migrated.latest.self.x,-68);assert.ok(migrated.latest.mine);migrated.ws.close();const a=await join(token),friends=[];for(let i=0;i<7;i++)friends.push(await join());const other=await join(randomUUID(),'OTHERCLAIM');await until(()=>a.latest.players.length===8);
    action(a,{type:'mineDig',x:-72.02,y:-4.35,z:30});await until(()=>a.latest.self.cargo.mass===12&&friends.every(c=>c.patches.length===1));assert.equal(other.patches.length,0);assert.equal(a.latest.self.wood,2);assert.equal(friends[0].latest.forest.trees[tree.id].logs,0);assert.equal(friends[0].latest.mine.props.filter(p=>p.type==='timber').length,1);assert.equal(friends[0].latest.mine.rubble[0].remaining,36);assert.equal(a.latest.mine.removed,undefined);assert.equal(friends[0].latest.mine.carts[0].cargo.goldMg,undefined);
    a.ws.send(JSON.stringify({type:'input',tool:'pick'}));await until(()=>friends.every(c=>c.latest.players.some(q=>q.id===p.id&&q.miningTool==='tunnelpick')));assert.equal(friends[0].latest.self.upgrades.includes('tunnelpick'),false);
    action(a,{type:'mineLoad',target:cart.id});await until(()=>a.latest.mine.carts[0].cargo.mass===112);action(a,{type:'hoistCall'});await until(()=>Math.abs(a.latest.mine.hoist.y+6)<.01);
    action(a,{type:'mineCart',target:cart.id});await until(()=>a.latest.self.mineCart===cart.id);action(a,{type:'hoistBoard'});await until(()=>a.latest.self.hoistRide);
    a.ws.send(JSON.stringify({type:'input',hoistUp:true}));await pause(150);a.ws.send(JSON.stringify({type:'input'}));await until(()=>a.latest.self.y>-3&&a.latest.self.y<5);
    await stop();const saved=JSON.parse(fs.readFileSync(path.join(dir,'worlds/MINEHOST.json')));assert.equal(saved.mine.carts[0].cargo.mass,112);assert.ok(saved.mine.carts[0].cargo.goldMg>=345.67);assert.equal(saved.mine.carts[0].operator,null);assert.equal(Object.values(saved.players).find(q=>q.id===p.id).hoistRide,false);assert.equal(saved.mine.hoist.riders.length,0);
    await start();const restored=await join(token);assert.equal(restored.welcome.mineBrushes.length,1);assert.equal(restored.latest.self.y,-6);assert.equal(restored.latest.self.wood,2);assert.equal(restored.latest.forest.trees[tree.id].logs,0);assert.equal(restored.latest.mine.props.filter(p=>p.type==='timber').length,1);assert.equal(restored.latest.mine.rubble[0].remaining,36);assert.equal(restored.latest.mine.hoist.cart,cart.id);
    assert.deepEqual(restored.latest.self.upgrades,['minerpick','mattock','tunnelpick']);restored.ws.send(JSON.stringify({type:'input',tool:'pick'}));await until(()=>restored.latest.self.miningTool==='tunnelpick');
    action(restored,{type:'hoistCall'});await until(()=>Math.abs(restored.latest.mine.hoist.y+6)<.01&&!restored.latest.mine.hoist.moving);action(restored,{type:'hoistBoard'});await until(()=>restored.latest.self.hoistRide);action(restored,{type:'hoistBoard'});await until(()=>!restored.latest.self.hoistRide&&restored.latest.mine.hoist.cart===null);assert.equal(restored.latest.mine.carts[0].y,-6);
    action(restored,{type:'mineRetrieve',target:cart.id});await until(()=>restored.latest.self.cargo.mass===24);assert.equal(restored.latest.mine.carts[0].cargo.mass,88);await stop();
  }finally{for(const s of sockets)s.terminate();if(host?.exitCode===null)host.kill();const resolved=path.resolve(dir);if(path.dirname(resolved)===path.resolve(os.tmpdir())&&path.basename(resolved).startsWith('gold-mine-host-'))fs.rmSync(resolved,{recursive:true,force:true});}
});
