import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';import {randomUUID,createHash} from 'node:crypto';import WebSocket from 'ws';
import {createRoom,createPlayer} from '../shared/simulation.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),rules=JSON.parse(fs.readFileSync(path.join(root,'shared/rules.json'))),pause=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){const t=Date.now();while(Date.now()-t<7000){if(await fn())return;await pause(35);}throw Error('Relic network timeout');}
test('eight real sockets share the unique find, restore its carrier, and receive one completed objective and payout',{timeout:30000},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'gold-relics-host-')),sockets=[];let host;fs.mkdirSync(path.join(dir,'worlds'));
 const token=randomUUID(),r=createRoom('RELICHOST',rules,'rush',8),p=createPlayer(createHash('sha256').update(token).digest('hex'),'Hunter',r),m=r.relics.items.find(t=>t.type==='motherlode');
 // A saved excavated pocket isolates transport/persistence from the separately tested digging gesture.
 Object.assign(p,{x:m.x,y:m.y-.8,z:m.z});r.mine.brushes.push({id:'fixture-pocket',a:{x:m.x,y:m.y,z:m.z},b:{x:m.x,y:m.y+.5,z:m.z},radius:2.8,floor:{x:m.x,y:p.y,z:m.z,sx:0,sz:0}});r.mine.terrainRevision++;fs.writeFileSync(path.join(dir,'worlds/RELICHOST.json'),JSON.stringify(r));
 const port=await new Promise(resolve=>{const n=net.createServer();n.listen(0,'127.0.0.1',()=>{const port=n.address().port;n.close(()=>resolve(port));});}),origin=`http://127.0.0.1:${port}`;
 async function start(){host=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),GOLD_FEVER_SAVE_DIR:path.join(dir,'worlds'),GOLD_FEVER_CONTROL_DIR:path.join(dir,'control')},stdio:'ignore',windowsHide:true});await until(async()=>{try{return(await fetch(origin+'/api/health')).ok;}catch{return false;}});}
 async function stop(){await fetch(origin+'/api/host/stop',{method:'POST',headers:{Authorization:`Bearer ${fs.readFileSync(path.join(dir,'control/host.key'),'utf8')}`}});await until(()=>host.exitCode!==null);}
 async function join(pass=randomUUID()){const ws=new WebSocket(`ws://127.0.0.1:${port}/crew`),c={ws,state:null,results:[]};sockets.push(ws);ws.on('message',raw=>{const msg=JSON.parse(raw);if(msg.type==='welcome')c.state=msg.state;if(msg.type==='snapshot')c.state=msg;if(msg.type==='result')c.results.push(msg);});await new Promise((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject);});ws.send(JSON.stringify({type:'join',token:pass,room:'RELICHOST',name:'Hunter',crewSize:8}));await until(()=>c.state);return c;}
 async function action(c,a){const n=c.results.length;c.ws.send(JSON.stringify({type:'action',action:a}));await until(()=>c.results.length>n);return c.results.at(-1);}
 try{await start();const a=await join(token),crew=[];for(let i=0;i<7;i++)crew.push(await join());await until(()=>crew.every(c=>c.state.relics.some(t=>t.id===m.id)));assert.equal((await action(a,{type:'relicTake',target:m.id})).ok,true);await until(()=>crew.every(c=>!c.state.relics.some(t=>t.id===m.id)));assert.equal((await action(crew[0],{type:'relicTake',target:m.id})).ok,false);
  await stop();await start();const restored=await join(token);assert.equal(restored.state.self.relics[0].id,m.id);assert.equal(restored.state.quest.completed,false);const friends=[];for(let i=0;i<7;i++)friends.push(await join());await action(restored,{type:'console',line:'tp assay'});assert.equal((await action(restored,{type:'sell'})).ok,true);await until(()=>friends.every(c=>c.state.quest.completed&&c.state.quest.earned===1500000));assert.equal(restored.state.cash,1500000);assert.equal((await action(restored,{type:'sell'})).ok,false);await stop();const saved=JSON.parse(fs.readFileSync(path.join(dir,'worlds/RELICHOST.json')));assert.equal(saved.relics.items.filter(t=>t.type==='motherlode').length,1);assert.equal(saved.relics.items.find(t=>t.id===m.id).state,'delivered');assert.equal(saved.cash,1500000);
 }finally{for(const s of sockets)s.terminate();if(host?.exitCode===null)host.kill();const resolved=path.resolve(dir);if(path.dirname(resolved)===path.resolve(os.tmpdir())&&path.basename(resolved).startsWith('gold-relics-host-'))fs.rmSync(resolved,{recursive:true,force:true});}
});
