import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRoom,createPlayer,act,snapshot,tick} from '../shared/simulation.mjs';
import {ensureRelics,tickRelics,relicClear,relicAction,relicSignal,relicLoad,relicSlow,RELIC_TYPES} from '../shared/relics.mjs';
import {toCell,keyOf,heightAt,baseHeight} from '../shared/world.mjs';import {exportWorld} from '../shared/export.mjs';import {resetMap} from '../shared/map-reset.mjs';
import {mineStep,mineRay,mineBodyClear} from '../shared/mine.mjs';
const rules=JSON.parse(fs.readFileSync(new URL('../shared/rules.json',import.meta.url)));
function setup(){const r=createRoom('RELICUNIT',rules),p=createPlayer('solo','Solo',r);return {r,p};}
function expose(r,t){const {ix,iz}=toCell(t.x,t.z);for(let x=-2;x<=2;x++)for(let z=-2;z<=2;z++)r.cells[keyOf(ix+x,iz+z)]={depth:2,digs:1};tickRelics(r);}
test('seeded valuables persist once; hidden positions do not appear in ordinary snapshots and solo shares one Motherlode',()=>{
 const {r,p}=setup(),a=JSON.stringify(r.relics);assert.equal(r.relics.items.filter(t=>t.type==='motherlode').length,1);assert.ok(r.relics.items.length>=40);assert.equal(ensureRelics(r),r.relics);assert.equal(JSON.stringify(r.relics),a);assert.equal(snapshot(r,p,rules,1000).relics.length,0);assert.equal(snapshot(r,p,rules,1000).quest.motherlode,'Still buried');assert.equal(snapshot(r,p,rules,1000).self.relicSignal,null);
 const other=createRoom('RELICOTHER',rules);assert.notEqual(JSON.stringify(other.relics.items),a);const exportCopy=exportWorld(r);assert.equal(exportCopy.relics.items.length,r.relics.items.length);const restored=JSON.parse(JSON.stringify(r));assert.deepEqual(ensureRelics(restored),r.relics);
});
test('ordinary starter excavation physically uncovers a coin; pickup validates range, free hands and shared ownership',()=>{
 const {r,p}=setup(),t=r.relics.items.find(t=>t.type==='coin'&&t.z>0&&t.x<0);assert.equal(relicClear(r,t),false);assert.equal(relicAction(r,p,{type:'relicTake',target:t.id}).ok,false);Object.assign(p,{x:t.x,z:t.z+1,y:heightAt(t.x,t.z+1,r.cells)});
 let now=1000;for(let n=0;n<24&&t.state==='buried';n++){const res=act(r,p,{type:'dig',x:t.x,z:t.z},rules,now);assert.equal(res.ok,true,res.message);p.cargo.mass=0;p.cargo.goldMg=0;now+=1100;tickRelics(r);}assert.equal(t.state,'exposed');assert.ok(snapshot(r,p,rules,now).relics.some(s=>s.id===t.id));
 Object.assign(p,{x:t.x+20});assert.equal(relicAction(r,p,{type:'relicTake',target:t.id}).ok,false);Object.assign(p,{x:t.x,z:t.z,y:heightAt(t.x,t.z,r.cells),shovel:{mass:6}});assert.equal(relicAction(r,p,{type:'relicTake',target:t.id}).ok,false);p.shovel=null;
 assert.equal(relicAction(r,p,{type:'relicTake',target:t.id}).ok,true);const friend=createPlayer('friend','Friend',r);Object.assign(friend,{x:p.x,y:p.y,z:p.z});assert.equal(relicAction(r,friend,{type:'relicTake',target:t.id}).ok,false);assert.equal(snapshot(r,p,rules,now).self.relics.length,1);assert.equal(snapshot(r,friend,rules,now).self.relics.length,0);assert.equal(snapshot(r,friend,rules,now).relics.some(s=>s.id===t.id),false);
});
test('rod purchase, look direction, proximity and depth change the survey without sending hidden coordinates',()=>{
 const {r,p}=setup();Object.assign(p,{x:-46,z:49,y:3.15});r.cash=18000;assert.equal(act(r,p,{type:'buy',item:'diviningrod'},rules,1000).ok,true);assert.equal(r.cash,0);const t=r.relics.items[0];r.relics.items=[t];Object.assign(p,{x:t.x,z:t.z+3,y:baseHeight(t.x,t.z),yaw:0,input:{tool:'rod'}});const toward=relicSignal(r,p);p.yaw=Math.PI;const away=relicSignal(r,p);assert.ok(toward.strength>away.strength);assert.match(toward.depth,/Below/);assert.equal('x' in toward,false);assert.equal('target' in toward,false);p.z+=30;assert.equal(relicSignal(r,p).strength,0);p.input.tool='shovel';assert.equal(relicSignal(r,p),null);p.upgrades=[];p.input.tool='rod';assert.equal(relicSignal(r,p),null);
});
test('three-slot satchel, dropping to a friend and Motherlode weight remain solo usable and survive reset/disconnect',()=>{
 const {r,p}=setup(),m=r.relics.items.find(t=>t.type==='motherlode');const items=r.relics.items.slice(0,4);Object.assign(p,{x:-25,z:58,y:3.15,yaw:0});for(const t of items)Object.assign(t,{x:p.x,y:p.y+.1,z:p.z,state:'exposed'});
 for(const t of items.slice(0,3))assert.equal(relicAction(r,p,{type:'relicTake',target:t.id}).ok,true);assert.equal(relicAction(r,p,{type:'relicTake',target:items[3].id}).ok,false);Object.assign(m,{x:p.x,y:p.y+.1,z:p.z,state:'exposed'});assert.equal(relicAction(r,p,{type:'relicTake',target:m.id}).ok,false);
 const friend=createPlayer('friend','Friend',r);Object.assign(friend,{x:p.x,y:p.y,z:p.z});assert.equal(relicAction(r,p,{type:'relicDrop'}).ok,true);assert.equal(relicAction(r,friend,{type:'relicTake',target:items[2].id}).ok,true);for(let i=0;i<2;i++)relicAction(r,p,{type:'relicDrop'});assert.equal(relicAction(r,p,{type:'relicTake',target:m.id}).ok,true);assert.equal(relicSlow(r,p),.7);assert.equal(relicLoad(snapshot(r,p,rules,1000).self),.7);assert.ok(rules.player.sprint*.7*.76>3.15);p.active=false;const saved=JSON.stringify(r.relics);tickRelics(r);assert.equal(JSON.stringify(r.relics),saved);resetMap(r);assert.equal(m.state,'carried');assert.equal(m.owner,p.id);
});
test('Bill sells finds with normal gold, pays once and records the shared completed objective without ending mining',()=>{
 const {r,p}=setup(),m=r.relics.items.find(t=>t.type==='motherlode');Object.assign(m,{state:'carried',owner:p.id});p.goldMg=1000;assert.equal(act(r,p,{type:'sell'},rules,1000).ok,false);Object.assign(p,{x:-37,z:64,y:3.15});const res=act(r,p,{type:'sell'},rules,1000);assert.equal(res.ok,true);assert.match(res.message,/MOTHERLODE CLAIMED/);assert.equal(r.cash,RELIC_TYPES.motherlode.value+3000);assert.equal(r.totalGoldMg,1000);const q=snapshot(r,p,rules,1000).quest;assert.equal(q.completed,true);assert.equal(q.earned,RELIC_TYPES.motherlode.value);assert.equal(q.delivered,1);assert.equal(act(r,p,{type:'sell'},rules,2000).ok,false);p.x=-15;p.z=20;assert.equal(act(r,p,{type:'dig',x:p.x,z:p.z},rules,3000).ok,true);assert.equal(JSON.parse(JSON.stringify(r)).relics.items.find(t=>t.id===m.id).state,'delivered');
});
test('roof rubble blocks a reburied find, and a visible deep item cannot be collected through solid rock',()=>{
 const {r,p}=setup(),t=r.relics.items.find(t=>t.type==='motherlode');Object.assign(t,{state:'exposed'});Object.assign(p,{x:t.x,y:t.y,z:t.z});assert.equal(relicAction(r,p,{type:'relicTake',target:t.id}).ok,false);tickRelics(r);assert.equal(t.state,'buried');p.active=false;const before=JSON.stringify(r.relics);tick(r,rules,.05,1000);assert.equal(JSON.stringify(r.relics),before);
});
test('a solo miner digs real rock down to the seeded Motherlode, collects it and climbs a purchased rope back out',()=>{
 const {r,p}=setup(),m=r.relics.items.find(t=>t.type==='motherlode');Object.assign(p,{x:m.x-.3,z:m.z,y:baseHeight(m.x-.3,m.z),upgrades:['tunnelpick','bucket'],kits:['rope'],input:{tool:'pick'}});mineStep(r.mine,p,{},0,.3);const start=p.y;assert.equal(act(r,p,{type:'deploy',item:'rope'},rules,1000).ok,true);let now=1000;
 for(let n=0;n<12&&m.state==='buried';n++){p.cargo={mass:0,goldMg:0,x:0,z:0};const h=mineRay(r.mine,{x:p.x,y:p.y+1.65,z:p.z},{x:.08,y:-Math.sqrt(1-.08**2),z:0},4.7);assert.ok(h);const res=act(r,p,{type:'mineDig',...h},rules,now+=1100);assert.equal(res.ok,true,res.message);for(let j=0;j<65;j++)mineStep(r.mine,p,{vertical:-1},0,.025);tickRelics(r);}
 assert.equal(m.state,'exposed');assert.ok(p.y<start-3);assert.equal(relicAction(r,p,{type:'relicTake',target:m.id}).ok,true);
 // Enter the rope from a widened side pocket: climbing must centre the body through the neck.
 p.cargo={mass:0,goldMg:0,x:0,z:0};const h=mineRay(r.mine,{x:p.x,y:p.y+1.65,z:p.z},{x:-1,y:0,z:0},4.7);assert.equal(act(r,p,{type:'mineDig',...h},rules,now+=1100).ok,true);p.yaw=Math.PI/2;mineStep(r.mine,p,{forward:1},2,.5);const rope=r.mine.props[0];assert.ok(Math.abs(p.x-rope.x)>.65);p.yaw=-Math.PI/2;for(let n=0;n<60&&Math.hypot(p.x-rope.x,p.z-rope.z)>.62;n++)mineStep(r.mine,p,{forward:1},1,.025);assert.ok(Math.hypot(p.x-rope.x,p.z-rope.z)<.65);
 for(let n=0;n<240;n++)mineStep(r.mine,p,{vertical:1},0,.025);assert.ok(p.y>start-.1);assert.ok(Math.hypot(p.x-rope.x,p.z-rope.z)<.1);assert.ok(mineBodyClear(r.mine,p.x,p.y,p.z));assert.equal(m.state,'carried');
});
