import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createRoom,createPlayer,act,tick,snapshot} from '../shared/simulation.mjs';import {FOREST_TREES,heightAt} from '../shared/world.mjs';import {WOOD,treeTarget} from '../shared/forestry.mjs';import {ensureSupports,tickStability,roofSupported,SUPPORT} from '../shared/supports.mjs';import {mineRay,mineStep,mineBodyClear,mineFloor} from '../shared/mine.mjs';import {emptyCargo} from '../shared/cargo.mjs';
const rules=JSON.parse(fs.readFileSync(new URL('../shared/rules.json',import.meta.url)));const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7);
function setup(){const r=createRoom('TIMBERTEST',rules),p=createPlayer('wood-player-123456','Dusty',r);return{r,p};}
function atTree(p,t){Object.assign(p,{x:t.x,z:t.z+2,y:heightAt(t.x,t.z),yaw:0});}
function fell(r,p,t,start=1000){atTree(p,t);for(let i=0;i<WOOD.hits;i++)assert.equal(act(r,p,{type:'chopTree',target:t.id,yaw:0,pitch:0},rules,start+i*700).ok,true);return start+WOOD.hits*700+1400;}
function gallery(){const {r,p}=setup();Object.assign(p,{x:-70,y:-6,z:30,yaw:Math.PI/2});let now=1000;for(let i=0;i<12;i++){p.cargo=emptyCargo();const h=mineRay(r.mine,{x:p.x,y:p.y+1.65,z:p.z},{x:-1,y:0,z:0},4.7);if(h)assert.equal(act(r,p,{type:'mineDig',...h},rules,now+=1100).ok,true);for(let j=0;j<20;j++)mineStep(r.mine,p,{forward:1},2,.025);}ensureSupports(r);return {r,p,now};}
function place(r,p,x,z=30,y=-6){Object.assign(p,{x,y,z});p.cargo=emptyCargo();p.wood=4;assert.equal(act(r,p,{type:'craftSupport'},rules,1000).ok,true);const a=act(r,p,{type:'deploy',item:'timber',x,y,z,yaw:Math.PI/2},rules,1100);assert.equal(a.ok,true,a.message);}
function isolate(r){const site=r.mine.risks.filter(s=>s.x<-77).at(-1);assert.ok(site);r.mine.risks=[site];return site;}
test('standing forest IDs match the scene; chopping needs reach, aim and five deliberate cooldown-limited hits',()=>{const {r,p}=setup(),t=FOREST_TREES[0];assert.equal(FOREST_TREES.length,140);assert.equal(act(r,p,{type:'chopTree',target:t.id,yaw:0,pitch:0},rules,1000).ok,false);atTree(p,t);assert.equal(treeTarget(r,p,0,0).id,t.id);assert.equal(act(r,p,{type:'chopTree',target:t.id,yaw:Math.PI,pitch:0},rules,1000).ok,false);act(r,p,{type:'chopTree',target:t.id,yaw:0,pitch:0},rules,1000);assert.equal(act(r,p,{type:'chopTree',target:t.id,yaw:0,pitch:0},rules,1100).ok,false);assert.equal(r.forest.trees[t.id].hits,1);for(let i=1;i<5;i++)act(r,p,{type:'chopTree',target:t.id,yaw:0,pitch:0},rules,1000+i*700);assert.equal(r.forest.trees[t.id].logs,6);assert.equal(treeTarget(r,p,0,0),null);assert.equal(p.wood,0);});
test('logs must finish falling; two miners cannot duplicate collection and wood can be dropped for a friend',()=>{const {r,p}=setup(),t=FOREST_TREES[0],now=fell(r,p,t),q=createPlayer('wood-friend-123456','Friend',r);atTree(q,t);assert.equal(act(r,p,{type:'collectWood',target:t.id},rules,now-2000).ok,false);assert.equal(act(r,p,{type:'collectWood',target:t.id},rules,now).ok,true);assert.equal(act(r,q,{type:'collectWood',target:t.id},rules,now).ok,false);assert.equal(p.wood,6);assert.equal(act(r,p,{type:'dropWood'},rules,now+1).ok,true);const stack=r.forest.stacks[0];assert.equal(act(r,q,{type:'collectWood',target:stack.id},rules,now+2).ok,true);assert.equal(q.wood,6);assert.equal(p.wood,0);assert.equal(r.forest.stacks.length,0);});
test('wood capacity accepts only available logs; supports consume four and cannot be bought for cash',()=>{const {r,p}=setup(),t=FOREST_TREES[0],now=fell(r,p,t);p.wood=22;act(r,p,{type:'collectWood',target:t.id},rules,now);assert.equal(p.wood,24);assert.equal(r.forest.trees[t.id].logs,4);act(r,p,{type:'craftSupport'},rules,now);assert.equal(p.wood,20);assert.deepEqual(p.kits,['timber']);p.x=-46;p.z=49;r.cash=100000;assert.equal(act(r,p,{type:'buy',item:'timber'},rules,now+1).ok,false);assert.equal(r.cash,100000);const before=JSON.stringify(p.kits);assert.equal(act(r,p,{type:'deploy',item:'timber',x:-74,y:-6,z:30,yaw:0},rules,now+2).ok,false);assert.equal(JSON.stringify(p.kits),before);});
test('frames about four metres apart protect a genuinely dug gallery and nearby branches for extended mining',()=>{const {r,p}=gallery();for(const x of[-74,-78,-82,-85])place(r,p,x);for(let i=0;i<180;i++)tickStability(r,1,10000+i*1000);assert.ok(r.mine.risks.every(s=>s.supported),JSON.stringify(r.mine.risks));assert.equal(r.mine.rubble.length,0);assert.ok(r.mine.props.every(s=>s.width>=1.5&&s.height>=1.8&&Number.isFinite(s.yaw)));});
test('unsupported roofs progress through creaking and danger; bracing at the warning cancels the collapse',()=>{const {r,p}=gallery(),s=isolate(r);let events=[];for(let i=0;i<75;i++)events.push(...tickStability(r,1,10000+i*1000));assert.equal(s.state,'danger');assert.ok(events.some(e=>e.effect?.type==='roofCrack'));place(r,p,s.x);assert.equal(s.stress,0);for(let i=0;i<120;i++)tickStability(r,1,100000+i*1000);assert.equal(r.mine.rubble.length,0);assert.equal(s.supported,true);});
test('an ignored roof caves into collidable rock and a solo miner scrambles clear without losing their cargo',()=>{const {r,p}=gallery(),s=isolate(r);Object.assign(p,{x:s.x,y:s.y,z:s.z});p.cargo={mass:10,goldMg:123,x:p.x,z:p.z};let events=[];for(let i=0;i<91;i++)events.push(...tickStability(r,1,10000+i*1000));assert.equal(r.mine.rubble.length,1);assert.ok(events.some(e=>e.mineRubble&&e.effect?.type==='caveIn'));assert.equal(mineBodyClear(r.mine,s.x,s.y,s.z),false);assert.ok(mineBodyClear(r.mine,p.x,p.y,p.z));near(p.cargo.mass,10);near(p.cargo.goldMg,123);assert.ok(p.muddyUntil>0);});
test('three real shovel cuts remove fallen rock without duplicating gold or original excavation',()=>{const {r,p}=gallery(),s=isolate(r);for(let i=0;i<91;i++)tickStability(r,1,10000+i*1000);const b=r.mine.rubble[0],count=r.mine.brushes.length,before=r.totalDugKg;Object.assign(p,{x:b.x+2.6,y:-6,z:30});p.cargo=emptyCargo();let gold=0,mass=0;for(let i=0;i<3;i++){const eye={x:p.x,y:p.y+1.65,z:p.z},point={x:b.x,y:b.y+b.height*b.remaining/b.total/2,z:b.z},len=Math.hypot(point.x-eye.x,point.y-eye.y,point.z-eye.z),dir={x:(point.x-eye.x)/len,y:(point.y-eye.y)/len,z:0},h=mineRay(r.mine,eye,dir,4.7);assert.ok(h);const plant=act(r,p,{type:'shovelPlant',...h},rules,200000+i*1300);assert.equal(plant.ok,true,JSON.stringify({plant,p,h}));const lift=act(r,p,{type:'shovelLift',pull:60},rules,200200+i*1300);assert.equal(lift.ok,true,JSON.stringify({lift,p,h}));gold+=p.shovel.goldMg;mass+=p.shovel.mass;p.shovel=null;}assert.equal(b.remaining,0);assert.equal(gold,0);near(mass,36);near(r.totalDugKg-before,36);assert.equal(r.mine.brushes.length,count);assert.equal(mineBodyClear(r.mine,b.x,-6,b.z),true);tickStability(r,1,205000);assert.ok(s.stress<35);place(r,p,b.x);for(let i=0;i<120;i++)tickStability(r,1,210000+i*1000);assert.equal(s.supported,true);assert.equal(r.mine.rubble.filter(b=>b.remaining>0).length,0);});
test('nearby supports cannot protect through an intervening wall or after their footing is dug away',()=>{const {r,p}=gallery();place(r,p,-78);const frame=r.mine.props[0];Object.assign(p,{x:-78,y:-6,z:30});const h=mineRay(r.mine,{x:p.x,y:p.y+1.65,z:p.z},{x:0,y:-1,z:0},4.7);assert.equal(act(r,p,{type:'mineDig',...h},rules,50000).ok,true);tickStability(r,1,51000);assert.equal(frame.undermined,true);assert.equal(roofSupported(r.mine,{x:-78,y:-6,z:30}),false);
const m={levels:[6,-6],removed:{},props:[{type:'timber',x:-80,y:-6,z:0}],brushes:[0,2.4].map(z=>({a:{x:-82,y:-5.4,z},b:{x:-78,y:-5.4,z},radius:.9,floor:{x:-80,y:-6,z,sx:0,sz:0}})),rubble:[]};assert.equal(roofSupported(m,{x:-80,y:-6,z:2.4}),false);});
test('offline rooms freeze roof danger; forest, wood, crafted frames and rubble survive JSON and snapshots',()=>{const {r,p}=gallery(),s=isolate(r);p.active=false;for(let i=0;i<200;i++)tick(r,rules,1,10000+i*1000);assert.equal(s.stress,0);p.active=true;p.wood=7;for(let i=0;i<91;i++)tickStability(r,1,10000+i*1000);const copy=JSON.parse(JSON.stringify(r));assert.equal(Object.values(copy.players)[0].wood,7);assert.equal(copy.mine.rubble[0].remaining,36);const snap=snapshot(r,p,rules,100000);assert.ok(snap.forest);assert.equal(snap.self.wood,7);assert.equal(snap.mine.risks,undefined);assert.ok(snap.mine.rubble.length);});
